# Generated by Django 3.2.4 on 2021-09-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.CharField(default=20, max_length=5),
            preserve_default=False,
        ),
    ]
