# Generated by Django 3.2.4 on 2021-10-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineOrder', '0002_invoice_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sub_total',
        ),
    ]
