# Generated by Django 3.2.4 on 2021-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineOrder', '0003_remove_invoice_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.CharField(default=100, max_length=5),
            preserve_default=False,
        ),
    ]
