# Generated by Django 3.2.4 on 2021-10-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineOrder', '0006_remove_invoice_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
            preserve_default=False,
        ),
    ]
